name: Vite React CI

on:
  push:
    branches:
      - main  # main ブランチに push されたら実行
  pull_request:
    branches:
      - main  # PR 作成時に実行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3  # リポジトリのコードを取得

      - name: Node.js のセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"  # npm のキャッシュを有効化（高速化）

      - name: 依存関係のインストール
        run: npm install

      - name: Vite ビルド
        run: npm run build

      - name: Vite 開発用サーバーのテスト（省略可）
        run: npm run dev -- --host &
        env:
          CI: true

      - name: Jest / Vitest のテスト実行
        run: npm test
